
package bigws.servidor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SoapWebService", targetNamespace = "http://Servidor.bigws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapWebService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addNote", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.AddNote")
    @ResponseWrapper(localName = "addNoteResponse", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.AddNoteResponse")
    public void addNote(
        @WebParam(name = "arg0", targetNamespace = "")
        Note arg0);

    /**
     * 
     * @return
     *     returns bigws.servidor.NoteBook
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaNotas", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.ListaNotas")
    @ResponseWrapper(localName = "listaNotasResponse", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.ListaNotasResponse")
    public NoteBook listaNotas();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteNote", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.DeleteNote")
    @ResponseWrapper(localName = "deleteNoteResponse", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.DeleteNoteResponse")
    public void deleteNote(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "showAll", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.ShowAll")
    @ResponseWrapper(localName = "showAllResponse", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.ShowAllResponse")
    public void showAll();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns bigws.servidor.NoteBook
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaNotasFilter", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.ListaNotasFilter")
    @ResponseWrapper(localName = "listaNotasFilterResponse", targetNamespace = "http://Servidor.bigws/", className = "bigws.servidor.ListaNotasFilterResponse")
    public NoteBook listaNotasFilter(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
